services:
  - type: web
    name: Backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: static_site
    name: Frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: frontend/build
    autoDeploy: true
    plan: free